### PR TITLE
Psf jacobian

### PR DESCRIPTION
**Pull request by jeremyneveu**
The goal of this PR is to speed-up Spectractor model computation:

- [x] faster matrix multiplications
- [x] faster PSF computations
- [x] faster Jacobian computations
- [x] faster wavelength calibration

We tested JAX but model is too complex to use automatic differentiation.

### CODE REVIEW

**Comment by jeremyneveu** [comment]
Tests with AuxTel exposure dataId = {"day_obs": 20230511, "seq_num": 252, "detector": 0} at USDF in DEBUG mode (slower because of plots):
| branch | total duration | 1D fit iteration [s] | FFM fit iteration [s] | final cost func value |
| ------- | -------------- | --------------| ---------------- | ----- |
| master |  14m50  | 0.3  | 66 | 1.5263e+05 | 
| psf_jacobian | 3m50 | 0.15 | 3.7 | 2e+06 |

**Review by mfisherlevine — APPROVED** [review]

**Comment by jeremyneveu** [comment]
Test with rebin=1 on dataId = {'day_obs': 20220316, 'seq_num': 330, 'detector':0}: 6GB memory usage. FFM in 22m with ~30s per FFM iterations.

**Comment by jeremyneveu** [comment]
@mfisherlevine, do you think we should move to version 2.7 or 3.0? Big parts of the core of the code has been optimized and rewritten.

**Comment by mfisherlevine** [comment]
I don't have any strong feelings as to 2.7 vs 3.0. If there are significant core algorithmic changes I can certainly see the argument for moving to 3.0, but it's totally up to you 🙂 (Also, you might want to make point-releases to iterate on this new code, in which case 3.0 also makes more sense)

**Comment by jeremyneveu** [comment]
Ok, then I switch to 3.0 :) Do you still approve the PR?

**Pull request merged**
